image: golang:1.8

stages:
  - test
  - build

before_script:
  - export GOPATH=$(dirname $CI_PROJECT_DIR)/go
  - mkdir -p $GOPATH/src
  - cd $GOPATH/src
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME

test:
  stage: test
  script:
    - go test ./...

build:
  stage: build
  script:
    - go build